<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alert Butonu</title>
    <style>
        /* İsteğe bağli: Butonu stilize etmek için CSS */
        #alertButton {
            padding: 10px 20px;
            font-size: 16px;
            cursor: pointer;
        }
    </style>
</head>
<body>

    <button id="alertButton" onclick="showAlert()">Alert Göster</button>

    <script>
        // JavaScript ile alert gösterme fonksiyonu
        function showAlert() {
            alert("Merhaba! Bu bir alert mesajidir.");
        }
    </script>

</body>
</html>